[package]
name = "natural-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "*"
llama-cpp-2 = { version = "0.1", features = ["cuda"] }
sqlparser = "0.55.0"
thiserror = "2.0.12"
encoding_rs = "0.8.35"
