[package]
name = "pgpt-extension"
version.workspace = true
edition.workspace = true

[dependencies]
pgrx = "0.13.0"
eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
